TOPDIR=		../../../

include $(TOPDIR)/misc/mk/config.mk
include $(TOPDIR)/misc/mk/common-$(ARCH).mk

LO_TARGET=  crc.lo

LO_OBJS=   	crc.o 



all: $(LO_TARGET)

include $(TOPDIR)/misc/mk/rules-common.mk
include $(TOPDIR)/misc/mk/rules-partition.mk

